//#define LOCALE
using System.Collections.Generic;

namespace CarePackageMod
{
    public class CarePackageList
    {
        public static CarePackageContainer[] GetPackages()
        {
            if (!DlcManager.IsExpansion1Active())
            {
                var result = new List<CarePackageContainer>
                {
                    new("Niobium", 5f),
                    new("Isoresin", 35f),
                    new("Fullerene", 1f),
                    new("Katairite", 1000f),
                    new("Diamond", 500f),
                    new(GeneShufflerRechargeConfig.ID, 1f),

                    new("SandStone", 1000f),
                    new("Dirt", 500f),
                    new("Algae", 500f),
                    new("OxyRock", 100f),
                    new("Water", 2000f),
                    new("Sand", 3000f),
                    new("Carbon", 3000f),
                    new("Fertilizer", 3000f),
                    new("Ice", 4000f),
                    new("Brine", 2000f),
                    new("SaltWater", 2000f),
                    new("Rust", 1000f),
                    new("Cuprite", 2000f),
                    new("GoldAmalgam", 2000f),
                    new("Copper", 400f),
                    new("Iron", 400f),
                    new("Lime", 150f),
                    new("Polypropylene", 500f),
                    new("Glass", 200f),
                    new("Steel", 100f),
                    new("Ethanol", 100f),
                    new("AluminumOre", 100f),
                    new("PrickleGrassSeed", 3f),
                    new("LeafyPlantSeed", 3f),
                    new("CactusPlantSeed", 3f),
                    new("MushroomSeed", 1f),
                    new("PrickleFlowerSeed", 2f),
                    new("OxyfernSeed", 1f),
                    new("ForestTreeSeed", 1f),
                    new(BasicFabricMaterialPlantConfig.SEED_ID, 3f),
                    new("SwampLilySeed", 1f),
                    new("ColdBreatherSeed", 1f),
                    new("SpiceVineSeed", 1f),
                    new("FieldRation", 5f),
                    new("BasicForagePlant", 6f),
                    new("CookedEgg", 3f),
                    new(PrickleFruitConfig.ID, 3f),
                    new("FriedMushroom", 3f),
                    new("CookedMeat", 3f),
                    new("SpicyTofu", 3f),
                    new("LightBugBaby", 1f),
                    new("HatchBaby", 1f),
                    new("PuftBaby", 1f),
                    new("SquirrelBaby", 1f),
                    new("CrabBaby", 1f),
                    new("DreckoBaby", 1f),
                    new("Pacu", 8f),
                    new("MoleBaby", 1f),
                    new("OilfloaterBaby", 1f),
                    new("LightBugEgg", 3f),
                    new("HatchEgg", 3f),
                    new("PuftEgg", 3f),
                    new("OilfloaterEgg", 3f),
                    new("MoleEgg", 3f),
                    new("DreckoEgg", 3f),
                    new("SquirrelEgg", 2f),
                    new("BasicCure", 3f),
                    new("Funky_Vest", 1f),
                };

                return [.. result];
            }
            else
            {
                List<CarePackageContainer> result = new List<CarePackageContainer>
                {
                    new("Niobium", 5f),
                    new("Isoresin", 35f),
                    new("Fullerene", 1f),
                    new("Katairite", 1000f),
                    new("Diamond", 500f),
                    new(GeneShufflerRechargeConfig.ID, 1f),

                    new("SandStone", 1000f),
                    new("Dirt", 500f),
                    new("Algae", 500f),
                    new("OxyRock", 100f),
                    new("Water", 2000f),
                    new("Sand", 3000f),
                    new("Carbon", 3000f),
                    new("Fertilizer", 3000f),
                    new("Ice", 4000f),
                    new("Brine", 2000f),
                    new("SaltWater", 2000f),
                    new("Rust", 1000f),
                    new("Cuprite", 2000f),
                    new("GoldAmalgam", 2000f),
                    new("Copper", 400f),
                    new("Iron", 400f),
                    new("Lime", 150f),
                    new("Polypropylene", 500f),
                    new("Glass", 200f),
                    new("Steel", 100f),
                    new("Ethanol", 100f),
                    new("AluminumOre", 100f),
                    new("PrickleGrassSeed", 3f),
                    new("LeafyPlantSeed", 3f),
                    new("CactusPlantSeed", 3f),
                    new("MushroomSeed", 3f),
                    new("PrickleFlowerSeed", 3f),
                    new("OxyfernSeed", 1f),
                    new("ForestTreeSeed", 1f),
                    new(BasicFabricMaterialPlantConfig.SEED_ID, 3f),
                    new("SwampLilySeed", 1f),
                    new("ColdBreatherSeed", 1f),
                    new("SpiceVineSeed", 1f),
                    new("FieldRation", 5f),
                    new("BasicForagePlant", 6f),
                    new("ForestForagePlant", 2f),
                    new("SwampForagePlant", 2f),
                    new("CookedEgg", 3f),
                    new(PrickleFruitConfig.ID, 3f),
                    new("FriedMushroom", 3f),
                    new("CookedMeat", 3f),
                    new("SpicyTofu", 3f),
                    new("WormSuperFood", 2f),
                    new("LightBugBaby", 1f),
                    new("HatchBaby", 1f),
                    new("PuftBaby", 1f),
                    new("SquirrelBaby", 1f),
                    new("CrabBaby", 1f),
                    new("DreckoBaby", 1f),
                    new("Pacu", 8f),
                    new("MoleBaby", 1f),
                    new("OilfloaterBaby", 1f),
                    new("DivergentBeetleBaby", 1f),
                    new("StaterpillarBaby", 1f),
                    new("LightBugEgg", 3f),
                    new("HatchEgg", 3f),
                    new("PuftEgg", 3f),
                    new("OilfloaterEgg", 3f),
                    new("MoleEgg", 3f),
                    new("DreckoEgg", 3f),
                    new("SquirrelEgg", 2f),
                    new("DivergentBeetleEgg", 2f),
                    new("StaterpillarEgg", 2f),
                    new("BasicCure", 3f),
                    new("Funky_Vest", 1f),
                };

                return [.. result];
            }
        }
    }
}
